# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a05871b0dc2e7aaaf81622263398cbdfd39e442a2a9e930f60a656d689a40af13a6688038f7d82b49d2bb84452b68819c620a33a2ba270a7064419581c38e45

test:
  secret_key_base: c74ed53bd48d142bcffaac8b78f7fb588b700291d03c34308031b69c4da9f71f7fea7a15de3b586cae2761c5a96aa33354061527b967f610e9039c3b4caccfc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
